# MTH8211: Algèbre linéaire numérique appliquée

## Laboratoire 1: introduction à Julia pour l'algèbre linéaire
Alexis Montoison, Dominique Orban

In [57]:
# la commande suivant sert uniquement à installer le module LinearAlgebra.
# Une fois exécutée, le module est installé dans l'environnement actuel.
# vous pouvez commenter cette commande une fois le module installé.

# ]add LinearAlgebra

In [58]:
using LinearAlgebra # importe le module LinearAlgebra

### **a) Création des vecteurs**

In [ ]:
v = [1; 2; 3]  # Vecteur de longueur 3
v = [1, 2, 3]  # Vecteur de longueur 3

In [ ]:
v = 1:2:21  # Entiers allant de 1 à 21 avec un pas de 2

In [ ]:
v = range(1, 5, length = 100)  # Vecteur de 100 points équidistants entre 1 et 5

### b) Création des matrices

In [6]:
M = [1.0 2.0 3.0; 
    4.0 5.0 6.0]
println("M est un ", typeof(M))
display(M)

M est un Matrix{Float64}


2×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0

In [8]:
M = zeros(2, 3) # Matrice contenant que des 0 de taille 2 x 3

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [9]:
M = ones(2, 3)  # Matrice contenant que des 1 de taille 2 x 3

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [10]:
M = I  # Matrice identité dont la dimension s'adapte aux opérations

UniformScaling{Bool}
true*I

In [11]:
M = Matrix(1.0*I, 3, 3) # Construction de la matrice identité 3 x 3 au format dense

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [13]:
# ]add SparseArrays

In [14]:
using SparseArrays

In [15]:
M = spzeros(2, 2)  # Création d'une matrice creuse de taille 2 x 2
M[1, 2] = 4
M[2, 2] = 1

1

In [16]:
x = [1, 2, 3]
y = [4, 5, 6, 7]
z = [8, 9, 10]
M = Tridiagonal(x, y, z)  # Création d'une matrice tridiagonale

4×4 Tridiagonal{Int64, Vector{Int64}}:
 4  8  ⋅   ⋅
 1  5  9   ⋅
 ⋅  2  6  10
 ⋅  ⋅  3   7

In [17]:
M = Bidiagonal(y, x, :L)  # Création d'une matrice bidiagonale inférieure

4×4 Bidiagonal{Int64, Vector{Int64}}:
 4  ⋅  ⋅  ⋅
 1  5  ⋅  ⋅
 ⋅  2  6  ⋅
 ⋅  ⋅  3  7

In [18]:
M = [1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16]
M = [1 2 3 4;
    5 6 7 8;
    9 10 11 12;
    13 14 15 16]

4×4 Matrix{Int64}:
  1   2   3   4
  5   6   7   8
  9  10  11  12
 13  14  15  16

In [19]:
LowerTriangular(M)  # Triangle inférieur de M

4×4 LowerTriangular{Int64, Matrix{Int64}}:
  1   ⋅   ⋅   ⋅
  5   6   ⋅   ⋅
  9  10  11   ⋅
 13  14  15  16

In [65]:
tril(M)

4×4 Matrix{Float64}:
 0.572287   0.0       0.0       0.0
 0.0329479  0.370313  0.0       0.0
 0.800345   0.925085  0.706034  0.0
 0.841534   0.749641  0.848604  0.446105

In [20]:
UpperTriangular(M)  # Triangle supérieur de M

4×4 UpperTriangular{Int64, Matrix{Int64}}:
 1  2   3   4
 ⋅  6   7   8
 ⋅  ⋅  11  12
 ⋅  ⋅   ⋅  16

In [66]:
triu(M)

4×4 Matrix{Float64}:
 0.572287  0.00109098  0.824707   0.981351
 0.0       0.370313    0.0422158  0.522937
 0.0       0.0         0.706034   0.0547024
 0.0       0.0         0.0        0.446105

In [21]:
UnitLowerTriangular(M)  # Triangle strictement inférieur de M avec diagonale unitaire

4×4 UnitLowerTriangular{Int64, Matrix{Int64}}:
  1   ⋅   ⋅  ⋅
  5   1   ⋅  ⋅
  9  10   1  ⋅
 13  14  15  1

In [22]:
UnitUpperTriangular(M)  # Triangle strictement supérieur de M avec diagonale unitaire

4×4 UnitUpperTriangular{Int64, Matrix{Int64}}:
 1  2  3   4
 ⋅  1  7   8
 ⋅  ⋅  1  12
 ⋅  ⋅  ⋅   1

In [23]:
M = M + ones(Int64, 4,4) * im

4×4 Matrix{Complex{Int64}}:
  1+1im   2+1im   3+1im   4+1im
  5+1im   6+1im   7+1im   8+1im
  9+1im  10+1im  11+1im  12+1im
 13+1im  14+1im  15+1im  16+1im

In [24]:
S = Symmetric(M, :L)  # Matrice symétrique basée sur le triangle inférieur de M

4×4 Symmetric{Complex{Int64}, Matrix{Complex{Int64}}}:
  1+1im   5+1im   9+1im  13+1im
  5+1im   6+1im  10+1im  14+1im
  9+1im  10+1im  11+1im  15+1im
 13+1im  14+1im  15+1im  16+1im

In [25]:
H = Hermitian(M, :L)  # Matrice hermitienne basée sur le triangle inférieur de M

4×4 Hermitian{Complex{Int64}, Matrix{Complex{Int64}}}:
  1+0im   5-1im   9-1im  13-1im
  5+1im   6+0im  10-1im  14-1im
  9+1im  10+1im  11+0im  15-1im
 13+1im  14+1im  15+1im  16+0im

In [26]:
M1 = sprand(2, 2, 0.5)  # Matrice aléatoire de taille 2 x 2 avec une densité moyenne de 0.5
M2 = sprand(3, 3, 0.7)  # Matrice aléatoire de taille 3 x 3 avec une densité moyenne de 0.7
BM = blockdiag(M1, M2)  # Matrice bloc diagonale

5×5 SparseMatrixCSC{Float64, Int64} with 9 stored entries:
 0.159416   ⋅          ⋅         ⋅          ⋅ 
  ⋅        0.0950322   ⋅         ⋅          ⋅ 
  ⋅         ⋅          ⋅        0.030655   0.350292
  ⋅         ⋅         0.703414  0.479501    ⋅ 
  ⋅         ⋅         0.740317  0.0158525  0.654424

### c) Manipulation des vecteurs et des matrices

In [27]:
M = [1+im 2-im; -1-im 3+2im]

2×2 Matrix{Complex{Int64}}:
  1+1im  2-1im
 -1-1im  3+2im

In [28]:
transpose(M)  # Matrice transposéee Mᵀ

2×2 transpose(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1+1im  -1-1im
 2-1im   3+2im

In [29]:
M'
adjoint(M)  # Matrice adjointe Mᴴ (transposée de la matrice conjuguée)

2×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1-1im  -1+1im
 2+1im   3-2im

In [30]:
M = [[1 2] [1 2]]  # Concaténation horizontale
M = hcat([1 2], [1 2])

1×4 Matrix{Int64}:
 1  2  1  2

In [31]:
M = [[1 2]; [1 2]]  #  Concaténation verticale
M = vcat([1 2], [1 2])

2×2 Matrix{Int64}:
 1  2
 1  2

In [32]:
v = 1:12  # Équivalent à 1:1:12
M = reshape(v, 3, 4)  # Redimensionnement d'un vecteur en une matrice 3 x 4

3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [33]:
M[:]  # Conversion d'une matrice en un vecteur

12-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12

In [34]:
reverse(M, dims = 1)  # Permutation des lignes

3×4 Matrix{Int64}:
 3  6  9  12
 2  5  8  11
 1  4  7  10

In [35]:
reverse(M, dims = 2)  # Permutation des colonnes

3×4 Matrix{Int64}:
 10  7  4  1
 11  8  5  2
 12  9  6  3

In [36]:
A = [1 2; 3 4]
repeat(A, 3, 4)  # Répétion de A, 3 fois dans la dimension des lignes et 4 fois dans la dimension des colonnes

6×8 Matrix{Int64}:
 1  2  1  2  1  2  1  2
 3  4  3  4  3  4  3  4
 1  2  1  2  1  2  1  2
 3  4  3  4  3  4  3  4
 1  2  1  2  1  2  1  2
 3  4  3  4  3  4  3  4

In [37]:
M = rand(4, 4)
A = similar(M) # Construction d'une matrice similaire à M (type / dimensions)
A = similar(M, 2, 2) # Contruction d'une matrice similaire à M avec des dimensions différentes

2×2 Matrix{Float64}:
 1.32068e-315  1.32068e-315
 1.32068e-315  1.32068e-315

### d) Accès aux composants d'un vecteur ou d'une matrice

In [38]:
M[2, 2]  # Accès au coefficient (2, 2) de M

0.37031338495258415

In [39]:
M[1:2, :]  # Accès aux lignes 1 à 2 de M

2×4 Matrix{Float64}:
 0.572287   0.00109098  0.824707   0.981351
 0.0329479  0.370313    0.0422158  0.522937

In [40]:
M[:, 1:3]  # Accès aux colonnes 1 à 3 de M

4×3 Matrix{Float64}:
 0.572287   0.00109098  0.824707
 0.0329479  0.370313    0.0422158
 0.800345   0.925085    0.706034
 0.841534   0.749641    0.848604

In [41]:
D = diag(M)  # Vecteur contenant la diagonale de la matrice M

4-element Vector{Float64}:
 0.5722871380885932
 0.37031338495258415
 0.7060336564808224
 0.44610514538205415

In [42]:
nrow, ncol = size(M)  # Dimensions de la matrice M 

(4, 4)

In [43]:
v = rand(3)
nvec = length(v) # Taille du vecteur v

3

### e) Opérations mathématiques

In [44]:
A = [1 2; 3 4]
B = [5 6; 7 8]

2×2 Matrix{Int64}:
 5  6
 7  8

In [45]:
A ⋅ B  # Produit scalaire de A et B
dot(A, B) # trace(AᵀB)

70

In [46]:
A * B  # Produit matriciel de A et B

2×2 Matrix{Int64}:
 19  22
 43  50

In [47]:
x = [10, 20]
y = similar(x)
mul!(y, A, x) # Produit matrice-vecteur en place

2-element Vector{Int64}:
  50
 110

In [48]:
A .* B  # Produit des coefficients termes à termes

2×2 Matrix{Int64}:
  5  12
 21  32

In [49]:
A^2  # Puissance d'une matrice (A * A)

2×2 Matrix{Int64}:
  7  10
 15  22

In [50]:
A.^2  # Puissance d'une matrice, coefficient par coefficient (A .* A)

2×2 Matrix{Int64}:
 1   4
 9  16

In [51]:
inv(A)  # Inverse d'une matrice

2×2 Matrix{Float64}:
 -2.0   1.0
  1.5  -0.5

In [52]:
det(A)  # Déterminant d'une matrice

-2.0

In [53]:
tr(A)  # Trace d'une matrice

5

In [54]:
val, vec = eigen(A)  # Valeurs propres et vecteurs propres de A

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 -0.3722813232690143
  5.372281323269014
vectors:
2×2 Matrix{Float64}:
 -0.824565  -0.415974
  0.565767  -0.909377

In [55]:
norm(A)  # Norme euclienne

5.477225575051661

In [56]:
b = A * ones(2)
x = A \ b  # Résolution du système linéaire Ax = b

2-element Vector{Float64}:
 0.9999999999999997
 1.0000000000000002

### f) Stockage de matrices creuses
Les gifs utilisés dans la suite du notebook proviennent de https://matteding.github.io/.

À l'opposé des matrices denses on peut se limiter au stockage des coefficients non nuls (*nnz*) pour les matrices creuses. On peut alors accélerer les opérations et réduire l'utilisation de la mémoire. Il existe différents formats de stockage pour les matrices creuses. Dans le cadre du cours on va se limiter aux formats COO, CSC et CSR.

![label_image](https://matteding.github.io/images/sparse_dense.gif)

__Format COO__

Il s'agit du format le plus facile à comprendre. Il utilise trois vecteurs pour stocker les lignes, les colonnes et les valeurs des coefficients non nuls.
Ce format est très pratique pour ajouter des coefficients à la matrices.

![label_image](https://matteding.github.io/images/coo.gif)

__Formats CSC et CSR__

Le format COO est adapté à la construction des matrices creuses mais ce n'est pas le format le plus performant pour les opérations. On préfére les formats compressés pour la lecture des données afin de limiter les accès en mémoire.

![label_image](https://matteding.github.io/images/csc.gif)

In [61]:
A = sprand(Float64, 5, 7, 0.3)

5×7 SparseMatrixCSC{Float64, Int64} with 5 stored entries:
  ⋅         ⋅        0.350009   ⋅    ⋅         ⋅    ⋅ 
 0.272558   ⋅         ⋅         ⋅    ⋅         ⋅    ⋅ 
  ⋅         ⋅         ⋅         ⋅   0.890583   ⋅    ⋅ 
  ⋅        0.372237  0.578266   ⋅    ⋅         ⋅    ⋅ 
  ⋅         ⋅         ⋅         ⋅    ⋅         ⋅    ⋅ 

In [63]:
println("pointeurs = ", A.colptr)
println("indices de lignes = ", A.rowval)
println("valeurs correspondantes = ", A.nzval)

pointeurs = [1, 2, 3, 5, 5, 6, 6, 6]
indices de lignes = [2, 4, 1, 4, 3]
valeurs correspondantes = [0.27255801441988936, 0.3722370253628997, 0.35000919004440767, 0.5782661078747937, 0.8905826677747116]


La différence entre le format COO et CSC / CSR est que les colonnes / lignes sont compressées à l'aide d'un vecteur représentant des pointeurs.

![label_image](https://matteding.github.io/images/csr.gif)

Le format CSR fonctionne de même manière analogue au format CSC. En fonction de la structure de la matrice, un des deux formats nécessite moins de mémoire.
En Julia les matrices creuses sont stockées au format CSC.